version: '3'
services:
    web:
        image: nginx:alpine
        container_name: test_nginx
        volumes:
            - "./web:/var/www/html"
            - "./hosts:/etc/nginx/conf.d"
        ports:
            - "80:80"
            - "443:443"
        environment:
            - NGINX_HOST=localhost
        restart: always
        depends_on:
            - php
            - mysqldb   
        networks:
            - internal
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        container_name: test_php
        volumes:
            - "./web:/var/www/html"
            - "./php:/usr/local/etc/php/custom.d"
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/custom.d:/usr/local/etc/php/conf.d"
        networks:
            - internal
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: test_phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
        networks:
            - internal    
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: test_mysql
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        networks:
            - internal    
networks:
        internal:
            driver: bridge
            ipam:
                driver: default
                config:
                    - subnet: 192.168.220.0/28            
